<?php
$html = '';
$html .= '<!DOCTYPE html>'."\n";
$html .= '<html>'."\n";
$html .= '	<head>'."\n";
$html .= '		<meta charset="utf-8"/>'."\n";
$html .= '		<title></title>'."\n";
$html .= '		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>'."\n";
$html .= '		<!-- stylesheet links -->'."\n";
$html .= '		<link rel="stylesheet" type="text/css" href="css/style.css"/>'."\n";
$html .= '		<!-- webfont links -->'."\n";
$html .= '		<link href=\'http://fonts.googleapis.com/css?family=Oswald:400,700\' rel=\'stylesheet\' type=\'text/css\'>'."\n";
$html .= '	</head>'."\n";
$html .= '	<body>'."\n";
$html .= '		<header>'."\n";
$html .= '			<div id="login-signup-search">'."\n";
$html .= '				<p><a href="user-profile.html">MY PROFILE</a> | <a href="#.html">LOGOUT</a></p>'."\n";
$html .= '				<form method="post" action="#">'."\n";
$html .= '					<input type="search" name="search">'."\n";
$html .= '				</form>'."\n";
$html .= '			</div>'."\n";
$html .= '			<section id="header-content">'."\n";
$html .= '				<h1><a href="index.html">TYPE CIRCUS</a></h1>'."\n";
$html .= '				<h2>A Weekly Typesetting Challenge</h2>'."\n";
$html .= '				<p>Each week <strong>TYPE CIRCUS</strong> sets a new typographic challenge for our members. It\'s a fun and engaging way to practice those essential typesetting skills and to showcase your talents to other designers.</p>'."\n";
$html .= '				<p><strong><a href="#">Sign up now and check out the latest challenge!</a></strong></p>'."\n";
$html .= '				<nav>'."\n";
$html .= '					<ul>'."\n";
$html .= '						<a href="index.html"><li>HOME</li></a>'."\n";
$html .= '						<a href="challenge.html"><li>CHALLENGE</li></a>'."\n";
$html .= '						<a href="about.html"><li>ABOUT</li></a>'."\n";
$html .= '					</ul>'."\n";
$html .= '				</nav>'."\n";
$html .= '			</section>'."\n";
$html .= '		</header>'."\n";
$html .= '		<section class="content" id="user-profile">'."\n";
$html .= '			<div id="user">'."\n";
$html .= '				<h3>JOE BLOGGS</h3>'."\n";
$html .= '				<img src="images/user-pic-JBloggs.jpg" class="winner-profile-pic" alt="picture of the winner\'s face"/>'."\n";
$html .= '				<h4>Student, part-time graphic designer.</h4>'."\n";
$html .= '				<h4>Wellington, NZ</h4>'."\n";
$html .= '				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod'."\n";
$html .= '				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,'."\n";
$html .= '				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo'."\n";
$html .= '				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse'."\n";
$html .= '				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non'."\n";
$html .= '				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>'."\n";
$html .= '				<h4><a href="#" class="orange-hover">www.joebloggsportfolio.com</a></h4>'."\n";
$html .= '				<p class="button"><a href="#">Edit Profile</a></p>'."\n";
$html .= '				<p class="button" id="orange-button"><a href="upload-design.html">Upload New Design</a></p>'."\n";
$html .= '			</div>'."\n";
$html .= '			<div>'."\n";
$html .= '				<h4>Designs:</h4>'."\n";
$html .= '				<div class="entry">'."\n";
$html .= '					<img src="images/user-pic-JBloggs.jpg" class="winner-profile-pic" alt="picture of the winner\'s face"/>'."\n";
$html .= '					<h4>Apple Crumble Challenge</h4>'."\n";
$html .= '				</div>'."\n";
$html .= '				<div class="entry">'."\n";
$html .= '					<img src="images/user-pic-JBloggs.jpg" class="winner-profile-pic" alt="picture of the winner\'s face"/>'."\n";
$html .= '					<h4>Charles Dickens Challenge</h4>'."\n";
$html .= '				</div>'."\n";
$html .= '				<div class="entry">'."\n";
$html .= '					<img src="images/user-pic-JBloggs.jpg" class="winner-profile-pic" alt="picture of the winner\'s face"/>'."\n";
$html .= '					<h4>Another Challenge</h4>'."\n";
$html .= '				</div>'."\n";
$html .= '				<div class="entry">'."\n";
$html .= '					<img src="images/user-pic-JBloggs.jpg" class="winner-profile-pic" alt="picture of the winner\'s face"/>'."\n";
$html .= '					<h4>Another Challenge</h4>'."\n";
$html .= '				</div>'."\n";
$html .= '			</div>'."\n";
$html .= '		</section>'."\n";
$html .= '		<footer>'."\n";
$html .= '			<nav>'."\n";
$html .= '				<ul>'."\n";
$html .= '					<a href="index.html"><li>HOME</li></a>'."\n";
$html .= '					<a href="challenge.html"><li>CHALLENGE</li></a>'."\n";
$html .= '					<a href="about.html"><li>ABOUT</li></a>'."\n";
$html .= '				</ul>'."\n";
$html .= '			</nav>'."\n";
$html .= '			<div id="social-media-links">'."\n";
$html .= '				<ul>'."\n";
$html .= '					<li><a href="#" id="fb-icon">Facebook</a></li>'."\n";
$html .= '					<li><a href="#" id="twt-icon">Twitter</a></li>'."\n";
$html .= '					<li><a href="#" id="tmblr-icon">Tumblr</a></li>'."\n";
$html .= '					<li><a href="#" id="rss-icon">RSS Feed</a></li>'."\n";
$html .= '				</ul>'."\n";
$html .= '			</div>'."\n";
$html .= '		</footer>'."\n";
$html .= '	</body>'."\n";
$html .= '</html>'."\n";
echo $html;
?>